version: "2"
services:
    data:
        image: busybox
        volumes:
            - ./mysql/data:/var/lib/mysql
    mysql:
        image: mysql:5.6
        container_name: "container_mysql"
        env_file: .env
        ports:
            - '3306:3306'
        volumes_from:
            - data
    wordpress:
        image: wordpress:latest
        container_name: "container_wordpress"
        ports:
            - "8080:80"
        links:
            - mysql:container_mysql
        environment:
            WORDPRESS_DB_HOST: "container_mysql:3306"
        env_file: .env
        volumes:
            - ./wp-content:/var/www/html/wp-content
